// @ts-nocheck
/* eslint-disable */
// This file was generated by tauri-specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async importClips(paths: string[] | null) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_clips", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importFolder(path: string | null) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listClips() : Promise<Result<ClipDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_clips") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateClip(id: string, update: ClipUpdate) : Promise<Result<ClipDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_clip", { id, update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteClip(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_clip", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playClip(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_clip", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSample() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_test_sample") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopClip(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_clip", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAll() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMasterVolume(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_master_volume", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listOutputDevices() : Promise<Result<OutputDeviceDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listInputDevices() : Promise<Result<InputDeviceDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_input_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startMicMeter(deviceName: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_mic_meter", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopMicMeter() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_mic_meter") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicLevel() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mic_level") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOutputDevices(config: OutputDevicesConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_output_devices", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setClipHotkey(id: string, hotkey: string | null) : Promise<Result<ClipDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clip_hotkey", { id, hotkey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setStopAllHotkey(hotkey: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_stop_all_hotkey", { hotkey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async suspendHotkeys() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_hotkeys") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeHotkeys() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_hotkeys") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async suggestAutoHotkeys(count: number) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_auto_hotkeys", { count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncIndexHotkeys(collectionId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_index_hotkeys", { collectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCollections() : Promise<Result<CollectionDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_collections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCollection(name: string, color: string | null) : Promise<Result<CollectionDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_collection", { name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCollection(id: string, update: CollectionUpdate) : Promise<Result<CollectionDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_collection", { id, update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCollection(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_collection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setClipCollections(clipId: string, collectionIds: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clip_collections", { clipId, collectionIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProfiles() : Promise<Result<ProfileDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createProfile(name: string) : Promise<Result<ProfileDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_profile", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateProfile(id: string, update: ProfileUpdate) : Promise<Result<ProfileDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_profile", { id, update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteProfile(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyProfile(id: string) : Promise<Result<ProfileDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDiagnostics() : Promise<Result<DiagnosticsDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_diagnostics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTheme(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_theme", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setOnboardingDone(done: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_onboarding_done", { done }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMicMix(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_mic_mix", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMicRoute(mode: MicRouteModeDto, duckingDb: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_mic_route", { mode, duckingDb }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setVadSound(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_vad_sound", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setVoiceTargetLufs(lufs: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_voice_target_lufs", { lufs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setIndexHotkeysEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_index_hotkeys_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMicDevice(device: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_mic_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPinnedClips(clipIds: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_pinned_clips", { clipIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMiniWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_mini_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hideMiniWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hide_mini_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVirtualCableStatus() : Promise<Result<VirtualCableStatusDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_virtual_cable_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect VB-CABLE (or similar), install if missing, then set secondary output.
 */
async ensureVirtualCable() : Promise<Result<VirtualCableEnsureResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_virtual_cable") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWatchedFolders() : Promise<Result<WatchedFolderDto[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_watched_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addWatchedFolder(path: string | null, collectionId: string | null) : Promise<Result<WatchedFolderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_watched_folder", { path, collectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeWatchedFolder(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_watched_folder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWatchedFolderEnabled(id: string, enabled: boolean) : Promise<Result<WatchedFolderDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_watched_folder_enabled", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { masterVolume: number; monitorEnabled: boolean; monitorDevice: string | null; secondaryDevice: string | null; stopAllHotkey: string | null; theme: string; activeProfileId: string | null; onboardingDone: boolean; 
/**
 * Legacy mirror: true when mic_route_mode is Mix or Ducking (voice present when idle).
 */
micMixEnabled: boolean; micRouteMode: MicRouteModeDto; duckingDb: number; vadSoundEnabled: boolean; voiceTargetLufs: number; indexHotkeysEnabled: boolean; 
/**
 * Physical microphone used for mic→CABLE mix (never CABLE Output).
 */
micDevice: string | null; pinnedClipIds: string[] }
export type ClipDto = { id: string; name: string; fileHash: string; ext: string; durationMs: number; volume: number; loopEnabled: boolean; hotkey: string | null; createdAt: string; position: number; peaks: number[] | null; trimStartMs: number; trimEndMs: number | null; fadeInMs: number; fadeOutMs: number; gainDb: number; restartOnPress: boolean; stopOthers: boolean; emoji: string | null; pinned: boolean; collectionIds: string[]; 
/**
 * Integrated loudness estimate (LUFS-ish); None until analyzed.
 */
integratedLufs: number | null; 
/**
 * Auto normalization gain toward voice target (dB).
 */
normGainDb: number }
export type ClipUpdate = { name: string | null; volume: number | null; loopEnabled: boolean | null; position: number | null; trimStartMs: number | null; trimEndMs: number | null; fadeInMs: number | null; fadeOutMs: number | null; gainDb: number | null; restartOnPress: boolean | null; stopOthers: boolean | null; emoji: string | null; pinned: boolean | null }
export type CollectionDto = { id: string; name: string; color: string; position: number; clipCount: number }
export type CollectionUpdate = { name: string | null; color: string | null; position: number | null }
export type DiagnosticsDto = { devices: OutputDeviceDto[]; sampleRate: number | null; warnings: string[]; monitorDevice: string | null; secondaryDevice: string | null; monitorEnabled: boolean }
export type ImportResult = { imported: ClipDto[]; duplicates: string[]; errors: string[] }
export type InputDeviceDto = { name: string; isDefault: boolean }
export type MicRouteModeDto = "mix" | "ducking" | "soundOnly"
export type OutputDeviceDto = { name: string; isDefault: boolean }
export type OutputDevicesConfig = { monitorEnabled: boolean; monitor: string | null; secondary: string | null }
export type ProfileDto = { id: string; name: string; monitorEnabled: boolean; monitorDevice: string | null; secondaryDevice: string | null; masterVolume: number; collectionId: string | null; isDefault: boolean; micRouteMode: MicRouteModeDto; duckingDb: number }
export type ProfileUpdate = { name: string | null; monitorEnabled: boolean | null; monitorDevice: string | null; secondaryDevice: string | null; masterVolume: number | null; collectionId: string | null; isDefault: boolean | null; micRouteMode: MicRouteModeDto | null; duckingDb: number | null }
export type VirtualCableEnsureResult = { status: VirtualCableStatusDto; message: string; rebootRequired: boolean }
export type VirtualCableStatusDto = { 
/**
 * A virtual playback endpoint suitable as Buddio secondary output exists.
 */
installed: boolean; 
/**
 * Preferred playback device name (e.g. CABLE Input), if found.
 */
playbackDevice: string | null; 
/**
 * Hint for Discord/Zoom input device.
 */
captureHint: string; 
/**
 * Current settings.secondary_device is a valid virtual playback device.
 */
configured: boolean; 
/**
 * Install finished but Windows still needs a reboot (or devices not visible yet).
 */
rebootRequired: boolean; 
/**
 * We asked for reboot earlier; onboarding should resume auto-config.
 */
pendingAfterReboot: boolean }
export type WatchedFolderDto = { id: string; path: string; collectionId: string | null; enabled: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
