mod commands;
mod db;
mod fake_devices;
mod managers;
mod models;

use std::sync::Arc;

use audio_engine::{AudioCommand, AudioEngineHandle, AudioEvent};
use managers::{
    CollectionsManager, FolderWatchManager, HotkeyManager, LibraryManager, ProfilesManager,
    SettingsManager,
};
use parking_lot::Mutex;
use tauri::{
    menu::{Menu, MenuItem},
    tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
    Emitter, Manager, WindowEvent,
};
use tracing::info;

fn show_mini(app: &tauri::AppHandle) {
    if let Some(mini) = app.get_webview_window("mini") {
        let _ = mini.show();
        let _ = mini.set_focus();
    }
    if let Some(main) = app.get_webview_window("main") {
        let _ = main.hide();
    }
}

fn show_main(app: &tauri::AppHandle) {
    if let Some(main) = app.get_webview_window("main") {
        let _ = main.show();
        let _ = main.unminimize();
        let _ = main.set_focus();
    }
}

fn hide_to_tray(app: &tauri::AppHandle) {
    if let Some(main) = app.get_webview_window("main") {
        let _ = main.hide();
    }
    // Capture UI can leave global shortcuts suspended if the recorder
    // unmounts without resume — re-arm before the app goes to tray.
    if let Some(state) = app.try_state::<AppState>() {
        if let Err(err) = state.hotkeys.ensure_active(app) {
            tracing::warn!(error = %err, "failed to re-arm hotkeys on hide-to-tray");
        }
    }
}

pub struct AppState {
    pub library: Arc<LibraryManager>,
    pub settings: Arc<SettingsManager>,
    pub hotkeys: Arc<HotkeyManager>,
    pub collections: Arc<CollectionsManager>,
    pub profiles: Arc<ProfilesManager>,
    pub folder_watch: Arc<FolderWatchManager>,
    pub audio: AudioEngineHandle,
    pub mic_meter: audio_engine::MicMeter,
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder =
        tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
            commands::import_clips,
            commands::import_folder,
            commands::list_clips,
            commands::update_clip,
            commands::delete_clip,
            commands::play_clip,
            commands::play_test_sample,
            commands::stop_clip,
            commands::stop_all,
            commands::set_master_volume,
            commands::list_output_devices,
            commands::list_input_devices,
            commands::start_mic_meter,
            commands::stop_mic_meter,
            commands::get_mic_level,
            commands::set_output_devices,
            commands::get_settings,
            commands::set_clip_hotkey,
            commands::set_stop_all_hotkey,
            commands::suspend_hotkeys,
            commands::resume_hotkeys,
            commands::suggest_auto_hotkeys,
            commands::sync_index_hotkeys,
            commands::list_collections,
            commands::create_collection,
            commands::update_collection,
            commands::delete_collection,
            commands::set_clip_collections,
            commands::list_profiles,
            commands::create_profile,
            commands::update_profile,
            commands::delete_profile,
            commands::apply_profile,
            commands::get_diagnostics,
            commands::set_theme,
            commands::set_onboarding_done,
            commands::set_mic_mix,
            commands::set_mic_route,
            commands::set_vad_sound,
            commands::set_voice_target_lufs,
            commands::set_index_hotkeys_enabled,
            commands::set_mic_device,
            commands::set_pinned_clips,
            commands::show_mini_window,
            commands::hide_mini_window,
            commands::get_virtual_cable_status,
            commands::ensure_virtual_cable,
            commands::list_watched_folders,
            commands::add_watched_folder,
            commands::remove_watched_folder,
            commands::set_watched_folder_enabled,
        ]);

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n/* eslint-disable */\n// This file was generated by tauri-specta. Do not edit.\n"),
            "../src/lib/bindings.ts",
        )
        .expect("failed to export typescript bindings");

    // Always refresh bindings when BUDDIO_GEN_BINDINGS=1 (CI / gen:bindings script).
    if std::env::var("BUDDIO_GEN_BINDINGS").ok().as_deref() == Some("1") {
        builder
            .export(
                specta_typescript::Typescript::default()
                    .header("// @ts-nocheck\n/* eslint-disable */\n// This file was generated by tauri-specta. Do not edit.\n"),
                "../src/lib/bindings.ts",
            )
            .expect("failed to export typescript bindings");
    }

    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.set_focus();
            }
        }))
        .plugin(
            tauri_plugin_log::Builder::new()
                .level(log::LevelFilter::Info)
                // Benign MP3 bit-reservoir quirks — spam the console on every decode.
                .level_for("symphonia_bundle_mp3", log::LevelFilter::Error)
                .level_for("symphonia_core", log::LevelFilter::Error)
                .build(),
        )
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            Some(vec!["--minimized"]),
        ))
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);

            // DevTools only when explicitly requested — default off even in `tauri dev`.
            #[cfg(debug_assertions)]
            if std::env::var("BUDDIO_DEVTOOLS").ok().as_deref() == Some("1") {
                if let Some(window) = app.get_webview_window("main") {
                    window.open_devtools();
                }
            }

            let app_data = app.path().app_data_dir().expect("resolve app data dir");
            std::fs::create_dir_all(&app_data)?;

            let db_path = app_data.join("database.sqlite");
            let assets_dir = app_data.join("assets");
            let conn = Arc::new(Mutex::new(db::open_and_migrate(&db_path)?));

            let library = Arc::new(LibraryManager::new(conn.clone(), assets_dir)?);
            let settings = Arc::new(SettingsManager::new(conn.clone()));
            let collections = Arc::new(CollectionsManager::new(conn.clone()));
            let profiles = Arc::new(ProfilesManager::new(conn.clone()));
            let folder_watch = Arc::new(FolderWatchManager::new(
                conn,
                library.clone(),
                collections.clone(),
            ));
            let hotkeys = Arc::new(HotkeyManager::new());
            // Own Win32 RegisterHotKey HWND on this UI thread (no tauri global-shortcut plugin).
            hotkeys.init_os(app.handle())?;

            let (audio, event_rx) = AudioEngineHandle::start();

            // Restore settings → audio engine
            let loaded = settings.load().unwrap_or_default();
            let _ = audio.send(AudioCommand::SetMasterVolume(loaded.master_volume));
            let _ = audio.send(AudioCommand::SetOutputs {
                monitor_enabled: loaded.monitor_enabled,
                monitor: loaded.monitor_device.clone(),
                secondary: loaded.secondary_device.clone(),
            });
            let _ = audio.send(AudioCommand::SetMicRoute {
                mode: loaded.mic_route_mode.to_engine(),
                ducking_db: loaded.ducking_db,
                input_device: loaded.mic_device.clone(),
            });
            let _ = audio.send(AudioCommand::SetVadSound {
                enabled: loaded.vad_sound_enabled,
            });

            // Preload all clips into hot cache
            if let Ok(clips) = library.list_clips() {
                for clip in clips {
                    let path = library.asset_path(&clip.file_hash, &clip.ext);
                    let _ = audio.send(AudioCommand::LoadClip {
                        clip_id: clip.id,
                        path,
                    });
                }
            }

            let state = AppState {
                library,
                settings,
                hotkeys: hotkeys.clone(),
                collections,
                profiles,
                folder_watch: folder_watch.clone(),
                audio,
                mic_meter: audio_engine::MicMeter::new(),
            };
            app.manage(state);

            if let Err(err) = folder_watch.start(app.handle().clone()) {
                tracing::warn!(error = %err, "failed to start folder watch");
            }

            // Forward audio events to the frontend
            let handle = app.handle().clone();
            std::thread::Builder::new()
                .name("buddio-audio-events".into())
                .spawn(move || {
                    while let Ok(event) = event_rx.recv() {
                        let payload = match event {
                            AudioEvent::PlaybackStarted { clip_id } => {
                                models::PlaybackEventPayload::Started { clip_id }
                            }
                            AudioEvent::PlaybackStopped { clip_id } => {
                                models::PlaybackEventPayload::Stopped { clip_id }
                            }
                            AudioEvent::DeviceWarning { message } => {
                                models::PlaybackEventPayload::DeviceWarning { message }
                            }
                            AudioEvent::Error { message } => {
                                models::PlaybackEventPayload::Error { message }
                            }
                        };
                        let _ = handle.emit("playback-event", payload);
                    }
                })?;

            // Register hotkeys after state is managed
            if let Err(err) = hotkeys.sync_from_library(app.handle()) {
                tracing::warn!(error = %err, "failed to sync hotkeys on startup");
            }

            // System tray → Buddio Mini
            let show_mini_item = MenuItem::with_id(app, "show_mini", "Abrir Buddio Mini", true, None::<&str>)?;
            let show_main_item = MenuItem::with_id(app, "show_main", "Abrir Buddio", true, None::<&str>)?;
            let stop_all_item = MenuItem::with_id(app, "stop_all", "Parar tudo", true, None::<&str>)?;
            let quit_item = MenuItem::with_id(app, "quit", "Sair", true, None::<&str>)?;
            let menu = Menu::with_items(
                app,
                &[&show_mini_item, &show_main_item, &stop_all_item, &quit_item],
            )?;

            let _tray = TrayIconBuilder::new()
                .icon(app.default_window_icon().cloned().expect("app icon"))
                .menu(&menu)
                .tooltip("Buddio")
                .on_menu_event(|app, event| match event.id.as_ref() {
                    "show_mini" => show_mini(app),
                    "show_main" => show_main(app),
                    "stop_all" => {
                        if let Some(state) = app.try_state::<AppState>() {
                            let _ = state.audio.send(AudioCommand::StopAll);
                        }
                    }
                    "quit" => app.exit(0),
                    _ => {}
                })
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        show_mini(tray.app_handle());
                    }
                })
                .build(app)?;

            if let Some(main) = app.get_webview_window("main") {
                let handle = app.handle().clone();
                main.on_window_event(move |event| {
                    if let WindowEvent::CloseRequested { api, .. } = event {
                        api.prevent_close();
                        hide_to_tray(&handle);
                    }
                });
            }

            info!(path = %app_data.display(), "Buddio ready");
            Ok(())
        })
        .on_window_event(|window, event| {
            if window.label() == "mini" {
                if let WindowEvent::CloseRequested { api, .. } = event {
                    api.prevent_close();
                    let _ = window.hide();
                }
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running Buddio");
}
